Repository premAI-io/prem-services, pull requests merged in 2023-10, with the labels that each got.

#117 Mistral-7B_q5, mac M1/M2 binaries
  .github/workflows/ci.yml
  .gitignore
  .vscode/settings.json
  cht-llama-cpp/README.md
  cht-llama-cpp/build-aarch64-apple-darwin.sh
  cht-llama-cpp/build.sh
  cht-llama-cpp/docker/cpu/Dockerfile
  cht-llama-cpp/main.py
  cht-llama-cpp/models.py
  cht-llama-cpp/requirements.txt
  cht-llama-cpp/routes.py
  cht-llama-cpp/tests/test_views.py
Labels: documentation, enhancement, ci

#119 cht-petals: new script and changes for managing installation and starting service without docker
  cht-petals/download.py
  cht-petals/main.py
  cht-petals/models.py
  cht-petals/requirements.txt
  cht-petals/setup-petals.sh
Labels: enhancement

#123 cht-llama-cpp: bump version
  cht-llama-cpp/README.md
  cht-llama-cpp/build-aarch64-apple-darwin.sh
  cht-llama-cpp/build.sh
  cht-llama-cpp/main.py
Labels: tech-debt

#121 cht-llama-cpp/build-darwin: use venv <= virtualenv
  .github/workflows/ci.yml
  cht-llama-cpp/README.md
  cht-llama-cpp/build-aarch64-apple-darwin.sh
Labels: tech-debt

#124 adds chatml prompt template as string to maintain configurability
  cht-llama-cpp/build-aarch64-apple-darwin.sh
  cht-llama-cpp/build.sh
  cht-llama-cpp/main.py
  cht-llama-cpp/models.py
  cht-llama-cpp/tests/test_views.py
Labels: bug
