Repository premAI-io/prem-services, pull requests merged in 2023-09, with the labels that each got.

#106 ci: debug external trigger
  .github/workflows/ci.yml
Labels: bug, ci

#108 Fix petals on amd
  cht-petals/build.sh
  cht-petals/docker/cpu/Dockerfile
  cht-petals/download.py
  cht-petals/models.py
Labels: enhancement

#112 ci: fix PR cancellations
  .github/workflows/ci.yml
Labels: bug, ci

#111 docker build speedups & memory reduction
  .github/workflows/ci.yml
  a2t-whisper/build.sh
  a2t-whisper/docker/cpu/Dockerfile
  a2t-whisper/docker/gpu/Dockerfile
  cdr-replit/build.sh
  cdr-replit/docker/gpu/Dockerfile
  cdr-replit/models.py
  cdr-t5/build.sh
  cdr-t5/docker/cpu/Dockerfile
  cdr-t5/models.py
  cht-dolly-v2/build.sh
  cht-dolly-v2/docker/gpu/Dockerfile
  cht-falcon/build.sh
  cht-falcon/docker/gpu/Dockerfile
  cht-falcon/utils.py
  cht-gorilla/build.sh
  cht-gorilla/docker/gpu/Dockerfile
  cht-gorilla/tests/test_views.py
  cht-llama-cpp/build.sh
  cht-llama-cpp/docker/cpu/Dockerfile
  cht-llama-cpp/routes.py
  cht-llama-v2/build.sh
  cht-llama-v2/docker/gpu/Dockerfile
  cht-llama-v2/utils.py
  cht-mpt/build.sh
  cht-mpt/docker/gpu/Dockerfile
  cht-mpt/utils.py
  cht-petals/build.sh
  cht-petals/docker/cpu/Dockerfile
  cht-petals/models.py
  cht-xgen/build.sh
  cht-xgen/docker/gpu/Dockerfile
  dfs-dalle/build.sh
  dfs-dalle/docker/gpu/Dockerfile
  dfs-dalle/download.py
  dfs-dalle/models.py
  dfs-dalle/requirements.txt
  dfs-diffusers/build.sh
  dfs-diffusers/docker/gpu/Dockerfile
  dfs-diffusers/download.py
  dfs-diffusers/models.py
  dfs-diffusers/routes.py
  ebd-all-minilm/build.sh
  ebd-all-minilm/docker/cpu/Dockerfile
  ebd-all-minilm/docker/gpu/Dockerfile
  ebd-all-minilm/routes.py
  pyproject.toml
  t2a-bark/build.sh
  t2a-bark/docker/cpu/Dockerfile
  t2a-bark/docker/gpu/Dockerfile
Labels: enhancement, ci, tech-debt
